/*
* Java bean class
* Created on 27 mars 2015 ( Date ISO 2015-03-27 - Time 12:03:45 )
* Generated by Telosys Tools Generator ( version 2.1.1 )
*/

package org.demo.repository;

import java.io.Serializable;


import org.springframework.data.repository.PagingAndSortingRepository;
import org.demo.bean.Country;

/**
 * Repository
 *
 * @author Telosys Tools Generator
 *
 */
public interface CountryRepository extends PagingAndSortingRepository<Country, String>
{

}
